
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl: update
  application:
    name: accenture-api
    version: "1.0.0"
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
server:
  port: ${SERVER_PORT:8080}



accenture:
  api:
    url: https://jsonplaceholder.typicode.com


